version: '2'

services:

  zookeeper:
    extends:
      file: docker-compose-base.yml
      service: zookeeper
    container_name: zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper:2888:3888

  kafka:
    extends:
      file: docker-compose-base.yml
      service: kafka
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  ca.org1.example.com:
    extends:
      file: docker-compose-base.yml
      service: ca
    container_name: ca.org1.example.com
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/a373e7901e683503b7781b0ec61dfa4a850840bf53d54d96658ecd0877a1e35f_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

  orderer.example.com:
    extends:
      file: docker-compose-base.yml
      service: orderer
    environment:
      - ORDERER_HOST=orderer.example.com
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka:9092]
      - ORDERER_KAFKA_VERBOSE=true
    container_name: orderer.example.com
    ports:
      - 7050:7050
    volumes:
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/etc/hyperledger/msp/orderer/msp
    depends_on:
      - kafka

  peer0.org1.example.com:
    extends:
      file: docker-compose-base.yml
      service: peer
    container_name: peer0.org1.example.com
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.example.com
      - couchdb

  couchdb:
    extends:
      file: docker-compose-base.yml
      service: couchdb
    container_name: couchdb
    ports:
      - 5984:5984
    environment:
      DB_URL: http://localhost:5984/member_db
