version: '2'

services:
  ca.org1.example.com:
    extends:
      file: docker-compose-base.yml
      service: ca
    container_name: ca.org1.example.com
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
      - BOOTSTRAP_USER_PASS=Admin:adminpw
      - FABRIC_CA_SERVER_CSR_CN=ca.org1.example.com
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/19ab65abbb04807dad12e4c0a9aaa6649e70868e3abd0217a322d89e47e1a6ae_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/ordererOrganizations/example.com/ca:/var/hyperledger/fabric-ca-server-config
      - ./crypto-config/ordererOrganizations/example.com:/var/hyperledger/fabric-ca-server
    ports:
      - 7054:7054

  orderer.example.com:
    extends:
      file: docker-compose-base.yml
      service: orderer
    container_name: orderer.example.com
    environment:
      - ORDERER_HOST=orderer.example.com
      - CONFIGTX_ORDERER_ORDERERTYPE=solo
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=false
      - ORDERER_GENERAL_GENESISPROFILE=SampleInsecureKafka
      - ORDERER_ABSOLUTEMAXBYTES=2000000
      - ORDERER_PREFERREDMAXBYTES=2000000
    volumes:
      - ./crypto-config/ordererOrganizations/example.com/msp:/var/hyperledger/msp
      - ./crypto-config/ordererOrganizations/example.com/tls:/var/hyperledger/tls
    ports:
      - 9050:7050

  peer0.org1.example.com:
    extends:
      file: docker-compose-base.yml
      service: peer
    container_name: peer0.org1.example.com
    environment:
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_LOCALMSPID=example.com
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@org1.example.com/tls/ca.crt
      - CORE_PEER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@org1.example.com/tls/client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@org1.example.com/tls/client.key
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/tls
    depends_on:
      - orderer.example.com
    ports:
      - 7051:7051
      - 7053:7053
